### ISSUE TITLE
module error

### ISSUE THREAD

**Issue by abalzi** [plewin/tp-link-modem-router#10]
Hi

I'm not an expert on nodejs and yarn, but I tried to solve by myself some issue.
I'm tring to run it on Raspberry Pi 4 with Ubuntu 21.04 64bit.
I've also installed the pkgs 

Setting up node-arrify (2.0.1-1) ...
Setting up node-is-buffer (2.0.5-1) ...
Setting up node-is-plain-obj (3.0.0-1) ...
Setting up node-kind-of (6.0.3+dfsg-1) ...
Setting up node-minimist (1.2.5+~cs5.3.1-2)

When I try to run your scripts I receive the below errors, what I missing?

**internal/process/esm_loader.js:74
    internalBinding('errors').triggerUncaughtException(
                              ^

Error [ERR_MODULE_NOT_FOUND]: Cannot find package 'minimist' imported from /usr/local/sms/tp-link-modem-router/sms-send.js
Did you mean to import minimist/index.js?
    at packageResolve (internal/modules/esm/resolve.js:650:9)
    at moduleResolve (internal/modules/esm/resolve.js:691:18)
    at Loader.defaultResolve [as _resolve] (internal/modules/esm/resolve.js:784:11)
    at Loader.resolve (internal/modules/esm/loader.js:100:40)
    at Loader.getModuleJob (internal/modules/esm/loader.js:246:28)
    at ModuleWrap.<anonymous> (internal/modules/esm/module_job.js:47:40)
    at link (internal/modules/esm/module_job.js:46:36) {
  code: 'ERR_MODULE_NOT_FOUND'
}**

**Comment by plewin** [comment]
Hey @abalzi 

It looks like a dependency was not installed correctly.

Did the `yarn install` command succeed ? If not, can you provide its ouput ?
