### ISSUE TITLE
SyntaxError: Unexpected identifier

### ISSUE THREAD

**Issue by BernardOOO** [plewin/tp-link-modem-router#7]
Hello all,
Archer MR600 v1 00000001
firmware 1.2.0 0.9.1 v0001.0 Build 200511 Rel.44954n
Node version v10.24.0
Os : Raspbian up to date on raspi A3+

pi@raspberrypi:~/tp-link-modem-router-master $ ./api-bridge.js
/home/pi/tp-link-modem-router-master/api-bridge.js:3
import fs from 'fs'
       ^^

SyntaxError: Unexpected identifier
    at Module._compile (internal/modules/cjs/loader.js:723:23)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:623:3)

I don't know anything in js :(
Can you help me ?

Edit : changing node.js and npm to the up to date releases and IT WORKS ! Thanks and sorry for the noise. :)

**Comment by plewin** [comment]
Hi, please upgrade to the latest stable nodejs. Seems the nodejs currently
installed is outdated.
Best regards,

**Comment by plewin** [comment]
Hi @BernardOOO do you still have issues with this ?

**Comment by plewin** [comment]
Closing because the issue has been solved.
